<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>8</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CurrencyCloud" Version="10.0.0" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.14.0" />
    <PackageReference Include="Polly" Version="8.6.5" />
  </ItemGroup>
</Project>