using System;
using Newtonsoft.Json;

namespace CurrencyCloud.Entity
{
    public class DemoFunding : Entity
    {
        public DemoFunding(decimal amount
                         , string currency
                         , string receiverAccountNumber)
        {
            // NOTE: IDs are client-side generated lowercase UUIDs for the demo funding endpoint so just generate one rather than requiring the user to provide it.
            //       (they can be created with uppercase but any subsequent calls that use the ID will fail validation if not lowercase)
            this.Id = Guid.NewGuid().ToString().ToLower(); 
            this.Amount = amount;
            this.Currency = currency;
            this.ReceiverAccountNumber = receiverAccountNumber;
        }

        [JsonConstructor]
        public DemoFunding()
        { }

        /// <summary>
        /// The unique UUID for the simulated fund.
        /// </summary>
        [Param]
        public string Id { get; set; }

        /// <summary>
        /// The account UUID the simulated fund was created for.
        /// </summary>
        public string AccountId { get; set; }

        /// <summary>
        /// The state of the simulated fund.
        /// </summary>
        public string State { get; set; }

        /// <summary>
        /// The sender's name.
        /// </summary>
        [Param]
        public string SenderName { get; set; }

        /// <summary>
        /// The sender's address.
        /// </summary>
        [Param]
        public string SenderAddress { get; set; }

        /// <summary>
        /// Two-digit sender country.
        /// </summary>
        [Param]
        public string SenderCountry { get; set; }

        /// <summary>
        /// Sender reference.
        /// </summary>
        [Param]
        public string SenderReference { get; set; }

        /// <summary>
        /// Sender account number.
        /// </summary>
        [Param]
        public string SenderAccountNumber { get; set; }

        /// <summary>
        /// Sender routing code.
        /// </summary>
        [Param]
        public string SenderRoutingCode { get; set; }

        /// <summary>
        /// A client or its sub-account's account number.
        /// </summary>
        [Param]
        public string ReceiverAccountNumber { get; set; }

        /// <summary>
        /// Routing code for a client or its sub-account.
        /// </summary>
        [Param]
        public string ReceiverRoutingCode { get; set; }

        /// <summary>
        /// Amount of the emulated transaction.
        /// </summary>
        [Param]
        public decimal? Amount { get; set; }

        /// <summary>
        /// Three-digit currency code.
        /// </summary>
        [Param]
        public string Currency { get; set; }

        /// <summary>
        /// Allows you to trigger approval or rejection behaviour.
        /// </summary>
        [Param]
        public string Action { get; set; }

        /// <summary>
        /// The reference generated by the system to identify the fund.
        /// </summary>
        public string ShortReference { get; set; }

        /// <summary>
        /// The date-time the SSI was added to the account.
        /// </summary>
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The date-time the SSI was last updated on the account.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }
    }
}